platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/Model.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala, platform-api/analytics-api/app/controllers/JobController.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/dataexhaust/DataExhaustUtils.scala
For Raw telemetry exhaust. It should read from channel-exhaust backup instead of reading from raw backup.
=> Data exhaust

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/Model.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/MetricsAPIService.scala, platform-api/analytics-api-core/src/test/resources/application.conf, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestMetricsAPIService.scala, platform-api/analytics-api/app/controllers/Metrics.scala, platform-api/analytics-api/conf/application.conf, platform-api/analytics-api/conf/routes
[Story link](https://project-sunbird.atlassian.net/browse/SB-8948)
=> Issue #SB-8949 feat: Dialcode metrics API

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdatePortalMetrics.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdatePortalMetrics.scala
This PR is related to calculating portal metrics from reading cassandra table[device profile and workf flow summay]
=> Issue SB-9190 fix: Portal Metrics changes

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDeviceProfileDB.scala
@anandp504 @sowmya-dixit Please review
=> Issue #000 fix: Handle null value for updated_date in UpdateDeviceProfileDB

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceRegisterService.scala
@anandp504 @sowmya-dixit  please review the code
=> SB-10661 chore: Add district information in device profile

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDeviceProfileDB.scala
@anandp504 @sowmya-dixit please review
=> SB-10661 fix: add state_custom, state_code_custom and district_custom columns for device profile updater

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/model/ETBCoverageSummaryModel.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/model/TestETBCoverageSummaryModel.scala
@anandp504 @sowmya-dixit  @sunilpes Please review.
=> Issue SB-10661 chore: Fix nested dialcode value for not to exceed size limit

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDialcodeUsageDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDialCodeUsageDB.scala, platform-scripts/database/data.cql
@sunilpes @sowmya-dixit @anandp504 Please review
=> Issue SB-11478 chore: Add objectType for GraphUpdateEvent in UpdateDialCodeUsageDB

Jenkinsfile, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceRegisterService.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDeviceProfileDB.scala, platform-scripts/database/data.cql
=> Issue #000 feat: Merge release-1.14-S3 to master

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala
Sample log event: 
```js
{"eid":"LOG","ets":1555419334767,"ver":"3.0","mid":"92ADB2CCC16FF395B9D3F227A4DDE21A","actor":{"id":"","type":"System"},"context":{"channel":"analytics.api","pdata":{"id":"AnalyticsAPI","ver":"3.0","pid":"registerDevice","model":null},"env":"analytics","sid":null,"did":null,"cdata":null,"rollup":null},"object":null,"edata":{"type":"api-access","duration":0,"score":0,"rating":0.0,"index":0,"status":"500","data":"API is Failed due to Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.","sort":null,"correlationid":null,"filters":null,"size":0},"@timestamp":"2019-04-16T12:55:34+00:00"}
```
=>  Device register api to log the errors message

platform-framework/analytics-core/src/main/scala/org/ekstep/analytics/framework/util/RestUtil.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/JobFactory.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/updater/ContentRatingUpdater.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateContentRating.scala, platform-modules/batch-models/src/test/resources/application.conf, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/updater/TestContentRatingUpdater.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateContentRating.scala
@anandp504 @sunilpes Please review
=> Issue #SB-12275 feat: Content Rating data product implementation

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateContentRating.scala, platform-modules/batch-models/src/test/resources/application.conf, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateContentRating.scala
=> Issue #SB-10302 fix: get content list druid query

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateContentRating.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateContentRating.scala
=> Issue #SB-10302 fix: end date for replay scenario

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateContentRating.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateContentRating.scala
=> Issue #SB-10302 refactor: Log error message

pom.xml
=> Issue #000 feat: Include platform-modules in pom.xml

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDeviceProfileDB.scala
@anandp504  @sunilpes @sowmya-dixit Please review this pr
=> [UPDATE DEVICE PROFILE DB]  Removed the channel field in the data product

platform-modules/adhoc-scripts/src/main/scala/ProcessFailedEvents.scala
@anandp504 @sunilpes Please review
=> Adhoc script for duration string type fix and replay for failed telemetry

platform-api/analytics-api/app/controllers/DeviceController.scala
in API response, `ts` parameter is not updating with current DateTime due to declaring the entire response as constant
=> Issue #SB-13220 fix: analytics API response

platform-modules/adhoc-scripts/src/main/es-script/copy_index.sh, platform-modules/adhoc-scripts/src/main/es-script/create-alias.sh, platform-modules/adhoc-scripts/src/main/es-script/delete_index.sh
Create alias to index shell script
=> Adhoc script update

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/CourseMetricsJob.scala
Issue link : https://project-sunbird.atlassian.net/browse/SB-13692
=> [SB-13692 ]Course Dashboard CSV Column order issue 

.gitignore, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala
=> Issue #000 feat: Update device first access as part of device register api

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/CourseMetricsJob.scala
Changed the field name from `completion on` to `Completion Date`
=> [SB-13801] Course Dashboard update

platform-api/analytics-api-core/pom.xml, platform-api/analytics-api/pom.xml, platform-framework/analytics-core/pom.xml
Reverts project-sunbird/sunbird-analytics#102
=> Revert "Issue #000 feat: Upgrade jackson lib version for security fixes"

platform-framework/analytics-core/src/main/scala/org/ekstep/analytics/framework/dispatcher/ScriptDispatcher.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/ConsumptionReportsJob.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/JobFactory.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/model/DailyConsumptionReportModel.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/model/TestDailyConsumptionReportsModel.scala
@sowmya-dixit @sunilpes 
Changes to schedule the adhoc consumption reports (python scripts) using JobManager by invoking the ScriptDispatcher
=> Issue #SB-13727 feat: Scheduling adhoc consumption reports using JobManager

platform-framework/analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala, platform-modules/batch-models/pom.xml, platform-modules/batch-models/src/main/resources/log4j2.xml
=> Issue #SC-1098 fix: Es multiple version issues

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/model/ExperimentDefinitionModel.scala
=> Issue #SC-1098 : Fixed device experiment issue while saving to es

platform-framework/analytics-job-driver/pom.xml
=> #SC-1027: Added appending Transformer in analytics-job-driver pom.xml

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/AssessmentMetricsJob.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/util/AssessmentReportUtil.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/util/ESUtil.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/TestAssessmentMetricsJob.scala
1.  Improving the performance by caching the report data frame 
2. Saving the report into an elastic search index immediately once the report is uploaded to azure.
=> Assessment data product performance issue fix

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/AssessmentMetricsJob.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/util/ESUtil.scala
Removed the unnecessary creation of spark conf
=> [Assessment DP] Elastic search issue fix

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api/app/controllers/DeviceController.scala, platform-api/analytics-api/conf/routes
=> GetDeviceProfile API mock implementation and DeviceRegisterAPI changes

.circleci/config.yml, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/updater/TestUpdateDeviceProfileDB.scala
=> DeviceProfileUpdater changes for schema change in device_profile cassandra table

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/model/DruidQueryProcessingModel.scala, platform-modules/batch-models/src/main/scala/org/ekstep/analytics/updater/UpdateDeviceProfileDB.scala
Added `api_last_updated_on` column to device profile updater data product.
=> Issue #SB-15355 fix: Device profile updater bug fix

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala
=> GetDeviceProfile API fix to handle empty user declared location.

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/StateAdminReportJob.scala
Converted String to List[String]
=> SC#1407 Fix schema type for userids attribute

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/AssessmentMetricsJob.scala
This patch is related to avoid creating multiple es indexes while running the job
=> Issue #SB-15582 fix: Indexing report into elastic search 

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/AssessmentMetricsJob.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/TestAssessmentMetricsJob.scala
Removing quotes for the score and max score column
=> Removing quotes for the score and total score

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/StateAdminReportJob.scala
User name column has been added.
Some int values have been changed to strings as per PRD.
Removed un-used functions.
Couldn't test as I used to for some reason after pulling in latest code. Submitting for review (will continue my efforts to bring it up).
=> SB-15907 Add name in the report

platform-framework/analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala, platform-framework/analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala, platform-framework/analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestCommonUtil.scala, platform-framework/analytics-job-driver/src/main/scala/org/ekstep/analytics/framework/driver/BatchJobDriver.scala, platform-framework/analytics-job-driver/src/test/resources/application.conf, platform-modules/batch-models/src/test/resources/application.conf
Generates and pushes METRIC event to kafka at the end of each job execution.
=> Metrics instrumentation for data products

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceProfileService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceProfileService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceRegisterService.scala, platform-api/analytics-api/app/Global.scala, platform-api/analytics-api/app/controllers/DeviceController.scala, platform-api/analytics-api/conf/application.conf
@SanthoshVasabhaktula 
1. Separate out the DeviceProfile api methods to a separate actor.
2. Instantiate a separate RedisUtil object for the DeviceRegisterService and DeviceProfileService actors.
=> Issue #SB-15961 feat: Fix RedisConnection issue for DeviceProfile api

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DruidHealthCheckService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/experiment/ExperimentService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/APILogger.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/CacheUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/CommonUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/ElasticsearchService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/H2DBUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/RedisUtil.scala, platform-api/analytics-api-core/src/test/resources/application.conf, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestCacheRefreshActor.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceRegisterService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDruidHealthCheckService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/experiment/TestExperimentService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestCacheUtil.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestCommonUtil.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestElasticsearchService.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestH2DBUtil.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestRedisUtil.scala, platform-api/analytics-api/conf/application.conf
Test case fix and code coverage improvement for Analytics API
=> Issue #SC-1484 update: test case fix and code coverage

platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/report/TestStateAdminGeoReportJob.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/report/TestStateAdminReportJob.scala
removed invalid test-cases
modified existing one
=> Issue #SC-1523 removed invalid test-cases and modified existing one

platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceProfileService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/SaveMetricsActor.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/CacheUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/H2DBUtil.scala, platform-api/analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/RedisUtil.scala, platform-api/analytics-api-core/src/test/resources/application.conf, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestCacheRefreshActor.scala, platform-api/analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestDeviceRegisterService.scala, platform-api/analytics-api/app/controllers/Application.scala, platform-api/analytics-api/app/controllers/DeviceController.scala, platform-api/analytics-api/app/modules/ActorInjector.scala, platform-api/analytics-api/conf/application.conf, platform-api/analytics-api/test/ApplicationSpec.scala
=> Issue #SB-16362 feat: Redis conn fix for device profile service

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/report/AssessmentMetricsJob.scala
This patch is related to index the report azure URL into elastic search assessment index.
=> Assessment report job fix

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/report/StateAdminGeoReportJob.scala, platform-modules/batch-models/src/test/scala/org/ekstep/analytics/job/report/TestStateAdminGeoReportJob.scala
@SanthoshVasabhaktula : Please review it.
=> #SC-1592 | User detail report zip generation added

platform-modules/batch-models/src/main/scala/org/ekstep/analytics/job/report/StateAdminGeoReportJob.scala
@SanthoshVasabhaktula : Please review it.
=> #SC-1592 | User detail report zip generation fixes added
